language: node_js

node_js: 
 - "node"

cache: npm

script: npm run build

before_deploy:
  - rm -rf node_modules
  - zip -r myganada-webservice.zip ./*
  - mkdir -p deploy
  - mv myganada-webservice.zip deploy/myganada-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myganada-build-s3
    region: us-east-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: master
